/**
 * This file was automatically generated by running scripts/migrate.ts.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Schema0 {
  before?: boolean
  after?: boolean
}

export type RuleOptions = [Schema0?]
