/**
 * This file is GENERATED by scripts/prepare.ts
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { RuleOptions } from './rule-options'

declare module 'eslint-define-config' {
  export interface CustomRuleOptions extends RuleOptions {}
}

export {}
