/**
 * This file was automatically generated by running scripts/migrate.ts.
 * DO NOT MODIFY IT BY HAND.
 */

export type Schema0 = '1tbs' | 'stroustrup' | 'allman'

export interface Schema1 {
  allowSingleLine?: boolean
}

export type RuleOptions = [Schema0?, Schema1?]
