/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RuleItem: typeof import('./docs/.vitepress/components/RuleItem.vue')['default']
    RuleList: typeof import('./docs/.vitepress/components/RuleList.vue')['default']
  }
}
