shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - packages/*
  - shared
catalogs:
  build:
    '@codecov/rollup-plugin': ^1.9.1
    tsdown: ^0.20.1
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@antfu/eslint-define-config': 1.23.0-2
    '@antfu/utils': ^9.3.0
    '@eslint/core': ^1.0.1
    '@eslint/css': ^0.14.1
    '@eslint/plugin-kit': ^0.5.1
    '@types/estraverse': ^5.1.7
    '@types/estree': ^1.0.8
    '@types/node': ^25.0.10
    '@types/picomatch': ^4.0.2
    '@types/semver': ^7.7.1
    '@typescript-eslint/parser': ^8.53.1
    '@typescript-eslint/utils': ^8.53.1
    change-case: ^5.4.4
    escape-string-regexp: ^5.0.0
    eslint: ^9.39.2
    eslint-plugin-eslint-plugin: ^7.3.0
    eslint-plugin-format: ^1.3.1
    execa: ^9.6.1
    fast-glob: ^3.3.3
    gray-matter: ^4.0.3
    jiti: ^2.6.1
    json-schema-to-typescript-lite: ^15.0.0
    jsonc-eslint-parser: ^2.4.2
    lint-staged: ^16.2.7
    ohash: ^2.0.11
    prettier: ^3.8.1
    semver: ^7.7.3
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.1
    vue-tsc: ^3.2.3
  docs:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/ri': ^1.2.7
    '@shikijs/transformers': ^3.21.0
    '@shikijs/twoslash': ^3.21.0
    '@shikijs/vitepress-twoslash': ^3.21.0
    '@types/markdown-it-container': ^4.0.0
    '@vueuse/core': ^14.1.0
    fuse.js: ^7.1.0
    markdown-it-container: ^4.0.0
    shiki: ^3.21.0
    twoslash: ^0.3.6
    twoslash-eslint: ^0.3.6
    unocss: ^66.6.0
    unplugin-vue-components: ^31.0.0
    vitepress: ^1.6.4
    vue: ^3.5.27
  prod:
    '@eslint-community/eslint-utils': ^4.9.1
    '@typescript-eslint/types': ^8.53.1
    eslint-visitor-keys: ^4.2.1
    espree: ^10.4.0
    estraverse: ^5.3.0
    picomatch: ^4.0.3
  test:
    '@babel/eslint-parser': ^7.28.6
    '@babel/plugin-syntax-decorators': ^7.28.6
    '@babel/plugin-syntax-do-expressions': ^7.28.6
    '@babel/plugin-syntax-function-bind': ^7.28.6
    '@babel/preset-react': ^7.28.5
    '@vitest/coverage-v8': ^4.0.18
    '@vitest/ui': ^4.0.18
    eslint-vitest-rule-tester: ^3.0.1
    vitest: ^4.0.18
    vue-eslint-parser: ^10.2.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
