packages:
  - docs
  - packages/*
catalogs:
  build:
    '@codecov/rollup-plugin': ^1.9.1
    tsdown: ^0.12.9
  dev:
    '@antfu/eslint-config': ^4.17.0
    '@antfu/eslint-define-config': 1.23.0-2
    '@antfu/utils': ^9.2.0
    '@types/estraverse': ^5.1.7
    '@types/estree': ^1.0.8
    '@types/node': ^24.0.14
    '@types/picomatch': ^4.0.0
    '@types/semver': ^7.7.0
    '@typescript-eslint/parser': ^8.37.0
    '@typescript-eslint/utils': ^8.37.0
    change-case: ^5.4.4
    escape-string-regexp: ^5.0.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    execa: ^9.6.0
    fast-glob: ^3.3.3
    gray-matter: ^4.0.3
    jiti: ^2.4.2
    json-schema-to-typescript-lite: ^14.1.0
    lint-staged: ^16.1.2
    ohash: ^2.0.11
    prettier: ^3.6.2
    semver: ^7.7.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    vite: ^7.0.4
    vue-tsc: ^3.0.1
  docs:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/ri': ^1.2.5
    '@shikijs/transformers': ^3.8.0
    '@shikijs/twoslash': ^3.8.0
    '@shikijs/vitepress-twoslash': ^3.8.0
    '@types/markdown-it-container': ^2.0.10
    '@vueuse/core': ^13.5.0
    fuse.js: ^7.1.0
    markdown-it-container: ^4.0.0
    shiki: ^3.8.0
    twoslash: ^0.3.2
    twoslash-eslint: ^0.3.2
    unocss: ^66.3.3
    unplugin-vue-components: ^28.8.0
    vitepress: ^1.6.3
    vue: ^3.5.17
  prod:
    '@eslint-community/eslint-utils': ^4.7.0
    '@typescript-eslint/types': ^8.37.0
    eslint-visitor-keys: ^4.2.1
    espree: ^10.4.0
    estraverse: ^5.3.0
    picomatch: ^4.0.3
  test:
    '@babel/eslint-parser': ^7.28.0
    '@babel/plugin-syntax-decorators': ^7.27.1
    '@babel/plugin-syntax-do-expressions': ^7.27.1
    '@babel/plugin-syntax-function-bind': ^7.27.1
    '@babel/preset-react': ^7.27.1
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint-vitest-rule-tester: ^2.2.0
    vitest: ^3.2.4
    vue-eslint-parser: ^10.2.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
