packages:
  - docs
  - packages/*
catalog:
  '@antfu/eslint-config': ^3.4.1
  '@antfu/eslint-define-config': 1.23.0-2
  '@antfu/ni': ^0.23.0
  '@antfu/utils': ^0.7.10
  '@babel/eslint-parser': ^7.25.1
  '@babel/plugin-syntax-decorators': ^7.24.7
  '@babel/plugin-syntax-do-expressions': ^7.24.7
  '@babel/plugin-syntax-function-bind': ^7.24.7
  '@babel/preset-react': ^7.24.7
  '@iconify-json/carbon': ^1.2.1
  '@iconify-json/ri': ^1.2.0
  '@rollup/plugin-alias': ^5.1.0
  '@rollup/plugin-commonjs': ^26.0.1
  '@rollup/plugin-node-resolve': ^15.2.3
  '@shikijs/transformers': ^1.16.2
  '@shikijs/twoslash': ^1.16.2
  '@shikijs/vitepress-twoslash': ^1.16.2
  '@types/estraverse': ^5.1.7
  '@types/estree': ^1.0.5
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/js-yaml': ^4.0.9
  '@types/json-schema': ^7.0.15
  '@types/markdown-it-container': ^2.0.10
  '@types/node': ^22.5.4
  '@types/picomatch': ^3.0.1
  '@types/semver': ^7.5.8
  '@typescript-eslint/parser': ^8.4.0
  '@typescript-eslint/utils': ^8.4.0
  '@unocss/reset': ^0.62.3
  '@vitest/coverage-v8': ^2.0.5
  '@vitest/ui': ^2.0.5
  '@vueuse/core': ^11.0.3
  acorn: ^8.12.1
  change-case: ^5.4.4
  escape-string-regexp: ^5.0.0
  eslint: ^9.10.0
  eslint-plugin-format: ^0.1.2
  eslint-visitor-keys: ^4.0.0
  eslint-vitest-rule-tester: ^0.6.1
  esno: ^4.7.0
  espree: ^10.1.0
  estraverse: ^5.3.0
  execa: ^9.3.1
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  fuse.js: ^7.0.0
  gray-matter: ^4.0.3
  jiti: ^1.21.6
  js-yaml: ^4.1.0
  json-schema: ^0.4.0
  json-schema-to-typescript-lite: ^14.1.0
  lint-staged: ^15.2.10
  markdown-it-container: ^4.0.0
  ohash: ^1.1.3
  picomatch: ^4.0.2
  pnpm: ^9.9.0
  prettier: ^3.3.3
  rimraf: ^6.0.1
  rollup: ^4.21.2
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  semver: ^7.6.3
  shiki: ^1.16.2
  simple-git-hooks: ^2.11.1
  taze: ^0.16.7
  tsx: ^4.19.0
  twoslash: ^0.2.11
  twoslash-eslint: ^0.2.11
  typescript: ^5.5.4
  unbuild: ^2.0.0
  unocss: ^0.62.3
  unplugin-vue-components: ^0.27.4
  vite: ^5.4.3
  vitepress: ^1.3.4
  vitest: ^2.0.5
  vue: ^3.5.3
  vue-tsc: ^2.1.6
