packages:
  - docs
  - packages/*
catalog:
  '@antfu/eslint-config': ^3.8.0
  '@antfu/eslint-define-config': 1.23.0-2
  '@antfu/ni': ^0.23.0
  '@antfu/utils': ^0.7.10
  '@babel/eslint-parser': ^7.25.9
  '@babel/plugin-syntax-decorators': ^7.25.9
  '@babel/plugin-syntax-do-expressions': ^7.25.9
  '@babel/plugin-syntax-function-bind': ^7.25.9
  '@babel/preset-react': ^7.25.9
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/ri': ^1.2.3
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-commonjs': ^28.0.1
  '@rollup/plugin-node-resolve': ^15.3.0
  '@shikijs/transformers': ^1.22.2
  '@shikijs/twoslash': ^1.22.2
  '@shikijs/vitepress-twoslash': ^1.22.2
  '@types/estraverse': ^5.1.7
  '@types/estree': ^1.0.6
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/js-yaml': ^4.0.9
  '@types/json-schema': ^7.0.15
  '@types/markdown-it-container': ^2.0.10
  '@types/node': ^22.8.4
  '@types/picomatch': ^3.0.1
  '@types/semver': ^7.5.8
  '@typescript-eslint/parser': ^8.12.2
  '@typescript-eslint/utils': ^8.12.2
  '@unocss/reset': ^0.63.6
  '@vitest/coverage-v8': ^2.1.4
  '@vitest/ui': ^2.1.4
  '@vueuse/core': ^11.1.0
  acorn: ^8.14.0
  change-case: ^5.4.4
  escape-string-regexp: ^5.0.0
  eslint: ^9.13.0
  eslint-plugin-format: ^0.1.2
  eslint-visitor-keys: ^4.2.0
  eslint-vitest-rule-tester: ^0.6.1
  esno: ^4.8.0
  espree: ^10.3.0
  estraverse: ^5.3.0
  execa: ^9.5.1
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  fuse.js: ^7.0.0
  gray-matter: ^4.0.3
  jiti: ^2.3.3
  js-yaml: ^4.1.0
  json-schema: ^0.4.0
  json-schema-to-typescript-lite: ^14.1.0
  lint-staged: ^15.2.10
  markdown-it-container: ^4.0.0
  ohash: ^1.1.4
  picomatch: ^4.0.2
  pnpm: ^9.12.3
  prettier: ^3.3.3
  rimraf: ^6.0.1
  rollup: ^4.24.3
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  semver: ^7.6.3
  shiki: ^1.22.2
  simple-git-hooks: ^2.11.1
  taze: ^0.17.2
  tsx: ^4.19.2
  twoslash: ^0.2.12
  twoslash-eslint: ^0.2.12
  typescript: ^5.6.3
  unbuild: ^2.0.0
  unocss: ^0.63.6
  unplugin-vue-components: ^0.27.4
  vite: ^5.4.10
  vitepress: ^1.4.2
  vitest: ^2.1.4
  vue: ^3.5.12
  vue-tsc: ^2.1.10
