packages:
  - docs
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.15.0
  '@antfu/eslint-define-config': 1.23.0-2
  '@antfu/utils': ^9.2.0
  '@types/estraverse': ^5.1.7
  '@types/estree': ^1.0.8
  '@types/node': ^24.0.3
  '@types/picomatch': ^4.0.0
  '@types/semver': ^7.7.0
  '@typescript-eslint/parser': ^8.34.1
  '@typescript-eslint/utils': ^8.34.1
  change-case: ^5.4.4
  escape-string-regexp: ^5.0.0
  eslint: ^9.29.0
  eslint-plugin-format: ^1.0.1
  execa: ^9.6.0
  fast-glob: ^3.3.3
  gray-matter: ^4.0.3
  jiti: ^2.4.2
  json-schema-to-typescript-lite: ^14.1.0
  lint-staged: ^16.1.2
  ohash: ^2.0.11
  pnpm: ^10.12.1
  prettier: ^3.5.3
  semver: ^7.7.2
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  tsx: ^4.20.3
  typescript: ^5.8.3
  vite: ^6.3.5
  vue-tsc: ^2.2.10
catalogs:
  build:
    '@codecov/rollup-plugin': ^1.9.1
    tsdown: ^0.12.9
  docs:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/ri': ^1.2.5
    '@shikijs/transformers': ^3.7.0
    '@shikijs/twoslash': ^3.7.0
    '@shikijs/vitepress-twoslash': ^3.7.0
    '@types/markdown-it-container': ^2.0.10
    '@vueuse/core': ^13.4.0
    fuse.js: ^7.1.0
    markdown-it-container: ^4.0.0
    shiki: ^3.7.0
    twoslash: ^0.3.1
    twoslash-eslint: ^0.3.1
    unocss: ^66.2.3
    unplugin-vue-components: ^28.7.0
    vitepress: ^1.6.3
    vue: ^3.5.17
  prod:
    '@eslint-community/eslint-utils': ^4.7.0
    '@typescript-eslint/types': ^8.34.1
    '@typescript-eslint/visitor-keys': ^8.34.1
    espree: ^10.4.0
    estraverse: ^5.3.0
    picomatch: ^4.0.2
  test:
    '@babel/eslint-parser': ^7.27.5
    '@babel/plugin-syntax-decorators': ^7.27.1
    '@babel/plugin-syntax-do-expressions': ^7.27.1
    '@babel/plugin-syntax-function-bind': ^7.27.1
    '@babel/preset-react': ^7.27.1
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint-vitest-rule-tester: ^2.2.0
    vitest: ^3.2.4
    vue-eslint-parser: ^10.1.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
