ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  # @babel/eslint-parser@7.28.6
  - semver@6.3.1
  # @codecov/rollup-plugin@1.9.1
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@octokit/endpoint@9.0.6'
  - undici@5.29.0

packages:
  - docs
  - packages/*
  - shared
catalogs:
  build:
    '@codecov/rollup-plugin': ^1.9.1
    tsdown: ^0.21.8
  dev:
    '@antfu/eslint-config': ^8.2.0
    '@antfu/eslint-define-config': 1.23.0-2
    '@antfu/utils': ^9.3.0
    '@eslint/core': ^1.2.1
    '@eslint/css': ^1.1.0
    '@eslint/markdown': ^8.0.1
    '@eslint/plugin-kit': ^0.7.1
    '@types/estree': ^1.0.8
    '@types/node': ^25.6.0
    '@types/picomatch': ^4.0.3
    '@types/semver': ^7.7.1
    '@typescript-eslint/parser': ^8.58.1
    '@typescript-eslint/utils': ^8.58.1
    bumpp: ^11.0.1
    change-case: ^5.4.4
    diff: ^9.0.0
    escape-string-regexp: ^5.0.0
    eslint: ^10.2.0
    eslint-plugin-eslint-plugin: ^7.3.2
    eslint-plugin-format: ^2.0.1
    execa: ^9.6.1
    fast-glob: ^3.3.3
    gray-matter: ^4.0.3
    jiti: ^2.6.1
    json-schema-to-typescript-lite: ^15.0.0
    jsonc-eslint-parser: ^3.1.0
    lint-staged: ^16.4.0
    ohash: ^2.0.11
    oxfmt: ^0.45.0
    oxlint: 1.55.0
    semver: ^7.7.4
    simple-git-hooks: ^2.13.1
    taze: ^19.11.0
    tsx: ^4.21.0
    typescript: ^6.0.2
    vite: ^8.0.8
    vue-tsc: ^3.2.6
  docs:
    '@iconify-json/carbon': ^1.2.20
    '@iconify-json/ri': ^1.2.10
    '@shikijs/transformers': ^4.0.2
    '@shikijs/twoslash': ^4.0.2
    '@shikijs/vitepress-twoslash': ^4.0.2
    '@types/markdown-it-container': ^4.0.0
    '@vueuse/core': ^14.2.1
    fuse.js: ^7.3.0
    markdown-it-container: ^4.0.0
    oxc-minify: ^0.125.0
    shiki: ^4.0.2
    twoslash: ^0.3.7
    twoslash-eslint: ^0.3.7
    unocss: ^66.6.8
    unplugin-vue-components: ^32.0.0
    vitepress: ^2.0.0-alpha.17
    vue: ^3.5.32
  prod:
    '@eslint-community/eslint-utils': ^4.9.1
    '@typescript-eslint/types': ^8.58.1
    '@typescript-eslint/visitor-keys': ^8.58.1
    espree: ^11.2.0
    picomatch: ^4.0.4
  test:
    '@babel/eslint-parser': ^7.28.6
    '@babel/plugin-syntax-decorators': ^7.28.6
    '@babel/plugin-syntax-do-expressions': ^7.28.6
    '@babel/plugin-syntax-function-bind': ^7.28.6
    '@babel/preset-react': ^7.28.5
    '@vitest/coverage-v8': ^4.1.4
    '@vitest/ui': ^4.1.4
    eslint-vitest-rule-tester: ^3.1.0
    vitest: ^4.1.4
    vue-eslint-parser: ^10.4.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
