packages:
  - docs
  - packages/*
  - shared
catalogs:
  build:
    '@codecov/rollup-plugin': ^1.9.1
    tsdown: ^0.15.2
  dev:
    '@antfu/eslint-config': ^5.3.0
    '@antfu/eslint-define-config': 1.23.0-2
    '@antfu/utils': ^9.2.0
    '@types/estraverse': ^5.1.7
    '@types/estree': ^1.0.8
    '@types/node': ^24.5.2
    '@types/picomatch': ^4.0.2
    '@types/semver': ^7.7.1
    '@typescript-eslint/parser': ^8.44.0
    '@typescript-eslint/utils': ^8.44.0
    change-case: ^5.4.4
    escape-string-regexp: ^5.0.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    execa: ^9.6.0
    fast-glob: ^3.3.3
    gray-matter: ^4.0.3
    jiti: ^2.5.1
    json-schema-to-typescript-lite: ^15.0.0
    lint-staged: ^16.1.6
    ohash: ^2.0.11
    prettier: ^3.6.2
    rolldown: 1.0.0-beta.35
    semver: ^7.7.2
    simple-git-hooks: ^2.13.1
    taze: ^19.6.0
    tsx: ^4.20.5
    typescript: ^5.8.3
    vite: ^7.1.6
    vue-tsc: ^3.0.7
  docs:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/ri': ^1.2.5
    '@shikijs/transformers': ^3.12.2
    '@shikijs/twoslash': ^3.12.2
    '@shikijs/vitepress-twoslash': ^3.12.2
    '@types/markdown-it-container': ^2.0.10
    '@vueuse/core': ^13.9.0
    fuse.js: ^7.1.0
    markdown-it-container: ^4.0.0
    shiki: ^3.12.2
    twoslash: ^0.3.4
    twoslash-eslint: ^0.3.4
    unocss: ^66.5.1
    unplugin-vue-components: ^29.0.0
    vitepress: ^1.6.4
    vue: ^3.5.21
  prod:
    '@eslint-community/eslint-utils': ^4.9.0
    '@typescript-eslint/types': ^8.44.0
    eslint-visitor-keys: ^4.2.1
    espree: ^10.4.0
    estraverse: ^5.3.0
    picomatch: ^4.0.3
  test:
    '@babel/eslint-parser': ^7.28.4
    '@babel/plugin-syntax-decorators': ^7.27.1
    '@babel/plugin-syntax-do-expressions': ^7.27.1
    '@babel/plugin-syntax-function-bind': ^7.27.1
    '@babel/preset-react': ^7.27.1
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint-vitest-rule-tester: ^2.2.1
    vitest: ^3.2.4
    vue-eslint-parser: ^10.2.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
