/**
 * This file was automatically generated by running scripts/migrate.ts.
 * DO NOT MODIFY IT BY HAND.
 */

export type Schema0 = 'always' | 'never'

export interface Schema1 {
  exceptAfterSingleLine?: boolean
  exceptAfterOverload?: boolean
}

export type RuleOptions = [Schema0?, Schema1?]
