module.exports = {
  'jsx-child-element-spacing': require('./jsx-child-element-spacing/jsx-child-element-spacing.js'),
  'jsx-closing-bracket-location': require('./jsx-closing-bracket-location/jsx-closing-bracket-location.js'),
  'jsx-closing-tag-location': require('./jsx-closing-tag-location/jsx-closing-tag-location.js'),
  'jsx-curly-brace-presence': require('./jsx-curly-brace-presence/jsx-curly-brace-presence.js'),
  'jsx-curly-newline': require('./jsx-curly-newline/jsx-curly-newline.js'),
  'jsx-curly-spacing': require('./jsx-curly-spacing/jsx-curly-spacing.js'),
  'jsx-equals-spacing': require('./jsx-equals-spacing/jsx-equals-spacing.js'),
  'jsx-first-prop-new-line': require('./jsx-first-prop-new-line/jsx-first-prop-new-line.js'),
  'jsx-indent': require('./jsx-indent/jsx-indent.js'),
  'jsx-indent-props': require('./jsx-indent-props/jsx-indent-props.js'),
  'jsx-max-props-per-line': require('./jsx-max-props-per-line/jsx-max-props-per-line.js'),
  'jsx-newline': require('./jsx-newline/jsx-newline.js'),
  'jsx-one-expression-per-line': require('./jsx-one-expression-per-line/jsx-one-expression-per-line.js'),
  'jsx-props-no-multi-spaces': require('./jsx-props-no-multi-spaces/jsx-props-no-multi-spaces.js'),
  'jsx-sort-props': require('./jsx-sort-props/jsx-sort-props.js'),
  'jsx-tag-spacing': require('./jsx-tag-spacing/jsx-tag-spacing.js'),
  'jsx-wrap-multilines': require('./jsx-wrap-multilines/jsx-wrap-multilines.js'),
  'self-closing-comp': require('./self-closing-comp/self-closing-comp.js'),
}
