/* GENERATED, DO NOT EDIT DIRECTLY */

import type { Linter } from 'eslint'

const config: Linter.Config = {
  rules: {
    'array-bracket-newline': 0,
    'array-bracket-spacing': 0,
    'array-element-newline': 0,
    'arrow-parens': 0,
    'arrow-spacing': 0,
    'block-spacing': 0,
    'brace-style': 0,
    'comma-dangle': 0,
    'comma-spacing': 0,
    'comma-style': 0,
    'computed-property-spacing': 0,
    'dot-location': 0,
    'eol-last': 0,
    'func-call-spacing': 0,
    'function-call-argument-newline': 0,
    'function-paren-newline': 0,
    'generator-star-spacing': 0,
    'implicit-arrow-linebreak': 0,
    'indent': 0,
    'jsx-quotes': 0,
    'key-spacing': 0,
    'keyword-spacing': 0,
    'line-comment-position': 0,
    'linebreak-style': 0,
    'lines-around-comment': 0,
    'lines-between-class-members': 0,
    'max-len': 0,
    'max-statements-per-line': 0,
    'multiline-comment-style': 0,
    'multiline-ternary': 0,
    'new-parens': 0,
    'newline-per-chained-call': 0,
    'no-confusing-arrow': 0,
    'no-extra-parens': 0,
    'no-extra-semi': 0,
    'no-floating-decimal': 0,
    'no-mixed-operators': 0,
    'no-mixed-spaces-and-tabs': 0,
    'no-multi-spaces': 0,
    'no-multiple-empty-lines': 0,
    'no-tabs': 0,
    'no-trailing-spaces': 0,
    'no-whitespace-before-property': 0,
    'nonblock-statement-body-position': 0,
    'object-curly-newline': 0,
    'object-curly-spacing': 0,
    'object-property-newline': 0,
    'one-var-declaration-per-line': 0,
    'operator-linebreak': 0,
    'padded-blocks': 0,
    'padding-line-between-statements': 0,
    'quote-props': 0,
    'quotes': 0,
    'rest-spread-spacing': 0,
    'semi': 0,
    'semi-spacing': 0,
    'semi-style': 0,
    'space-before-blocks': 0,
    'space-before-function-paren': 0,
    'space-in-parens': 0,
    'space-infix-ops': 0,
    'space-unary-ops': 0,
    'spaced-comment': 0,
    'switch-colon-spacing': 0,
    'template-curly-spacing': 0,
    'template-tag-spacing': 0,
    'wrap-iife': 0,
    'wrap-regex': 0,
    'yield-star-spacing': 0,
  },
}
export default config
