/**
 * This file was automatically generated by running scripts/migrate.ts.
 * DO NOT MODIFY IT BY HAND.
 */

export type Schema0 =
  | []
  | ['never']
  | []
  | ['always']
  | [
    'always',
    {
      allowNewlines?: boolean
    },
  ]

export type RuleOptions = [Schema0?]
