/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomWrapper: typeof import('./.vitepress/components/CustomWrapper.vue')['default']
    RuleItem: typeof import('./.vitepress/components/RuleItem.vue')['default']
    RuleList: typeof import('./.vitepress/components/RuleList.vue')['default']
  }
}
