name: autofix.ci

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  merge_group: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run update

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # v1.3.3
