name: Continuous Releases
on:
  push:
    branches:
      - main
      - v**
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0
      - name: Build
        run: pnpm build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish
        run: pnpx pkg-pr-new publish --compact --pnpm './packages/*'
