name: Continuous Releases
on:
  push:
    branches:
      - main
      - v**
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@e10bbede8ba835eaee8df633bb472d303aba8509
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpx pkg-pr-new publish --compact --pnpm './packages/*'
