name: Compressed Size
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  report-build-size-diff:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: '**/dist/**/*.{js,mjs,cjs,d.ts}'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
